target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
  pod 'sharedSwift', :path => '../shared'
  pod 'mokoMvvmFlowSwiftUI', :podspec => 'https://raw.githubusercontent.com/icerockdev/moko-mvvm/release/0.16.1/mokoMvvmFlowSwiftUI.podspec'
  pod 'FirebaseAnalyticsSwift'
  pod 'FirebaseInAppMessagingSwift', '> 10.12-beta'
end


